import assert from "node:assert/strict";
import { mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";
import test from "node:test";
import { LocalKnowledgeBase } from "../src/knowledge/index.js";
import { KnowledgePermissionError, type KnowledgeDocumentInput, type KnowledgeSource } from "../src/knowledge/schemas.js";
import { PlosDiscoveryProvider } from "../src/knowledge/plos-discovery.js";

const source: KnowledgeSource = {
  id: "test-source",
  name: "Test Source",
  publisher: "Test Publisher",
  rightsUrl: "https://allowed.test/terms",
  license: "CC BY 4.0",
  allowedCorpora: ["player_report"],
  allowedUrlPrefixes: ["https://allowed.test/docs/"],
  rights: { automatedFetch: false, persistentStorage: true, aiProcessing: true, display: true },
  rightsVerifiedAt: "2026-09-29",
  rightsNote: "Test fixture with explicit storage and AI permissions.",
};

const document: KnowledgeDocumentInput = {
  sourceId: source.id,
  corpus: "player_report",
  title: "A player report",
  url: "https://allowed.test/docs/player-1",
  author: "A Scout",
  publisher: source.publisher,
  publishedAt: "2026-09-01",
  license: source.license,
  attribution: "A Scout, Test Source, 2026",
  entityIds: ["player-1"],
  entityNames: ["Jonas Vale"],
  competition: "Open League",
  season: "2025/26",
  acquisition: "manual_import",
  content: "Jonas Vale is observed making frequent forward runs and pressing after losing possession. This is a qualitative report observation, not a measured match statistic.",
};

async function createFixtureBase(tempRoot: string) {
  const registryPath = path.join(tempRoot, "sources.json");
  await writeFile(registryPath, JSON.stringify([source]), "utf8");
  const base = new LocalKnowledgeBase({
    indexPath: path.join(tempRoot, "index"),
    registryPath,
    seedDocuments: [],
    embedder: {
      modelId: "test-embedding",
      async embed(text: string) {
        const value = text.toLocaleLowerCase().includes("pressing") ? 1 : 0.5;
        return [value, 1 - value];
      },
    },
  });
  return { base, registryPath };
}

test("knowledge ingestion rejects unregistered sources and unapproved automated fetching", async () => {
  const tempRoot = await mkdtemp(path.join(os.tmpdir(), "tactiscout-knowledge-policy-"));
  try {
    const { base } = await createFixtureBase(tempRoot);
    await assert.rejects(base.ingest({ ...document, sourceId: "unknown-source" }), KnowledgePermissionError);
    await assert.rejects(base.ingest({ ...document, acquisition: "authorized_fetch" }), /未获准自动抓取/);
    await assert.rejects(base.ingest({ ...document, url: "https://unlisted.test/player-1" }), /URL 不在来源/);
  } finally {
    await rm(tempRoot, { recursive: true, force: true });
  }
});

test("authorized local imports are persisted with provenance and searchable by corpus", async () => {
  const tempRoot = await mkdtemp(path.join(os.tmpdir(), "tactiscout-knowledge-index-"));
  try {
    const { base } = await createFixtureBase(tempRoot);
    const inserted = await base.ingest(document);
    const results = await base.search({ corpus: "player_report", query: "Jonas Vale forward runs", playerNames: ["Jonas Vale"], limit: 3 });
    const status = await base.status();

    assert.equal(inserted.chunkCount, 1);
    assert.equal(results[0]?.sourceId, source.id);
    assert.deepEqual(results[0]?.entityIds, ["player-1"]);
    assert.equal(results[0]?.license, source.license);
    assert.equal(status.playerReportChunks, 1);
    assert.equal(status.embeddingModel, "test-embedding");
  } finally {
    await rm(tempRoot, { recursive: true, force: true });
  }
});

test("methodology documents with no player entities can create a LanceDB index", async () => {
  const tempRoot = await mkdtemp(path.join(os.tmpdir(), "tactiscout-knowledge-empty-entities-"));
  try {
    const { base } = await createFixtureBase(tempRoot);
    const inserted = await base.ingest({ ...document, entityIds: [], entityNames: [] });
    assert.equal(inserted.chunkCount, 1);
  } finally {
    await rm(tempRoot, { recursive: true, force: true });
  }
});

test("an index cannot mix vectors generated by different embedding models", async () => {
  const tempRoot = await mkdtemp(path.join(os.tmpdir(), "tactiscout-knowledge-models-"));
  try {
    const { base, registryPath } = await createFixtureBase(tempRoot);
    await base.ingest(document);
    const incompatibleBase = new LocalKnowledgeBase({
      indexPath: path.join(tempRoot, "index"),
      registryPath,
      seedDocuments: [],
      embedder: {
        modelId: "different-test-embedding",
        async embed() { return [0.2, 0.8]; },
      },
    });

    await assert.rejects(
      incompatibleBase.search({ corpus: "player_report", query: "Jonas Vale report", playerNames: ["Jonas Vale"] }),
      /当前知识索引使用了其他 embedding 模型/,
    );
    await assert.rejects(
      incompatibleBase.ingest({ ...document, title: "A second report", url: "https://allowed.test/docs/player-2" }),
      /当前知识索引使用了其他 embedding 模型/,
    );
  } finally {
    await rm(tempRoot, { recursive: true, force: true });
  }
});

test("updated source permissions also restrict documents already in the index", async () => {
  const tempRoot = await mkdtemp(path.join(os.tmpdir(), "tactiscout-knowledge-revocation-"));
  try {
    const { base, registryPath } = await createFixtureBase(tempRoot);
    await base.ingest(document);
    await writeFile(registryPath, JSON.stringify([{
      ...source,
      allowedCorpora: ["methodology"],
      rights: { ...source.rights, aiProcessing: false },
    }]), "utf8");
    const refreshedBase = new LocalKnowledgeBase({
      indexPath: path.join(tempRoot, "index"),
      registryPath,
      seedDocuments: [],
      embedder: {
        modelId: "test-embedding",
        async embed() { return [1, 0]; },
      },
    });

    const results = await refreshedBase.search({ corpus: "player_report", query: "Jonas Vale report", playerNames: ["Jonas Vale"] });
    assert.deepEqual(results, []);
  } finally {
    await rm(tempRoot, { recursive: true, force: true });
  }
});

test("player report retrieval hard-filters documents by indexed player entity", async () => {
  const tempRoot = await mkdtemp(path.join(os.tmpdir(), "tactiscout-knowledge-entities-"));
  try {
    const { base } = await createFixtureBase(tempRoot);
    await base.ingest(document);
    await base.ingest({
      ...document,
      title: "Another player report",
      url: "https://allowed.test/docs/player-2",
      entityIds: ["player-2"],
      entityNames: ["Marco Silva"],
      content: "Marco Silva is observed making frequent forward runs and pressing after losing possession. This is a qualitative report observation, not a measured match statistic.",
    });

    const results = await base.search({
      corpus: "player_report",
      query: "forward runs and pressing",
      playerNames: ["Jonas Vale"],
      limit: 5,
    });
    const noEntityMatch = await base.search({
      corpus: "player_report",
      query: "forward runs and pressing",
      playerNames: ["Harry Kane"],
      limit: 5,
    });

    await assert.rejects(base.search({
      corpus: "player_report",
      query: "forward runs and pressing",
      playerNames: [],
      limit: 5,
    }), /必须提供至少一个球员实体名称/);

    assert.deepEqual(results.map((result) => result.entityNames), [["Jonas Vale"]]);
    assert.deepEqual(noEntityMatch, []);
  } finally {
    await rm(tempRoot, { recursive: true, force: true });
  }
});

test("the shipped source registry records its attribution and retrieval permissions", async () => {
  const contents = await readFile(new URL("../data/knowledge/sources.json", import.meta.url), "utf8");
  const [plosSource] = JSON.parse(contents) as KnowledgeSource[];
  assert.equal(plosSource.id, "plos-soccer-analysis-2024");
  assert.equal(plosSource.license, "CC BY 4.0");
  assert.equal(plosSource.rights.persistentStorage, true);
  assert.equal(plosSource.rights.aiProcessing, true);
  assert.ok(plosSource.rightsNote.includes("API"));
});

test("PLOS discovery returns metadata only and marks only registered article URLs ingestible", async () => {
  const registryPath = fileURLToPath(new URL("../data/knowledge/sources.json", import.meta.url));
  let requestedUrl: URL | undefined;
  const fetcher: typeof fetch = async (input) => {
    requestedUrl = new URL(input.toString());
    return new Response(JSON.stringify({ response: { docs: [
      {
        id: "10.1371/journal.pone.0298346",
        title_display: "Registered methods paper",
        author_display: ["Davidson", "Barrett"],
        publication_date: "2024-03-07",
        copyright: "Creative Commons Attribution License",
      },
      {
        id: "10.1371/journal.pone.0999999",
        title_display: "Unregistered paper",
        author_display: ["A Researcher"],
        publication_date: "2026-01-01",
        copyright: "Creative Commons Attribution License",
      },
    ] } }), { status: 200, headers: { "content-type": "application/json" } });
  };
  const candidates = await new PlosDiscoveryProvider(fetcher).discover("soccer performance analysis", { registryPath, limit: 2 });

  assert.equal(requestedUrl?.hostname, "api.plos.org");
  assert.equal(requestedUrl?.searchParams.get("rows"), "2");
  assert.equal(candidates[0]?.registeredForIngestion, true);
  assert.equal(candidates[1]?.registeredForIngestion, false);
  assert.equal(candidates[0]?.articleUrl, "https://journals.plos.org/plosone/article?id=10.1371%2Fjournal.pone.0298346");
});

test("PLOS正文抓取只访问已登记DOI并保留文章署名和许可", async () => {
  let requestCount = 0;
  const fetcher: typeof fetch = async () => {
    requestCount += 1;
    return new Response(JSON.stringify({ response: { docs: [{
      id: "10.1371/journal.pone.0298346",
      title_display: "Methods paper",
      author_display: ["Davidson", "Barrett"],
      publication_date: "2024-03-07",
      copyright: "This open access article is distributed under the Creative Commons Attribution License.",
      abstract: "This is a sufficiently long abstract about football performance analysis.",
      body: "<p>Indicators need match context &amp; practitioner interpretation.</p>",
    }] } }), { status: 200, headers: { "content-type": "application/json" } });
  };
  const provider = new PlosDiscoveryProvider(fetcher);
  const article = await provider.fetchRegisteredArticle("10.1371/journal.pone.0298346", {
    registryPath: fileURLToPath(new URL("../data/knowledge/sources.json", import.meta.url)),
  });

  assert.equal(article.acquisition, "authorized_fetch");
  assert.equal(article.corpus, "methodology");
  assert.match(article.content, /Indicators need match context & practitioner interpretation/);
  assert.match(article.attribution, /Davidson, Barrett/);
  assert.equal(requestCount, 1);

  await assert.rejects(provider.fetchRegisteredArticle("10.1371/journal.pone.0999999", {
    registryPath: fileURLToPath(new URL("../data/knowledge/sources.json", import.meta.url)),
  }), /尚无允许自动抓取/);
  assert.equal(requestCount, 1, "unregistered article should be rejected before requesting its body");
});
